CREATE TABLE contact (
  ID                   SERIAL,
  DISPLAY_NAME         VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_NAME         VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  CONTACT_DESCRIPTION  VARCHAR(255) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  LOCATION_ID           BIGINT UNSIGNED NULL,
  CONSTRAINT contact_p PRIMARY KEY(ID),
  CONSTRAINT contact_display_name_u UNIQUE(DISPLAY_NAME),
  CONSTRAINT contact_search_name_u UNIQUE(SEARCH_NAME),
  INDEX contact_location_if (LOCATION_ID),
  CONSTRAINT contact_location_f FOREIGN KEY (LOCATION_ID)
  REFERENCES address_location(ID)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = INNODB;

CREATE TABLE phone (
  ID                     SERIAL,
  DISPLAY_PHONE_NUMBER   VARCHAR(20) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_PHONE_NUMBER    VARCHAR(20) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  DESCRIPTION            VARCHAR(250) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  CONSTRAINT phone_p PRIMARY KEY(ID),
  CONSTRAINT phone_display_u UNIQUE(DISPLAY_PHONE_NUMBER),
  CONSTRAINT phone_search_u  UNIQUE(SEARCH_PHONE_NUMBER)
) ENGINE = INNODB;

CREATE TABLE contact_phone (
  PHONE_ID        BIGINT UNSIGNED NOT NULL,
  CONTACT_ID      BIGINT UNSIGNED NOT NULL,
  ORDINAL_INDEX   INT UNSIGNED NOT NULL,
  CONSTRAINT contact_phone_p PRIMARY KEY(PHONE_ID),
  CONSTRAINT contact_phone_contact_u UNIQUE(CONTACT_ID, ORDINAL_INDEX),
  CONSTRAINT contact_phone_phone_f FOREIGN KEY(PHONE_ID)
  REFERENCES phone(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT contact_phone_contact_f FOREIGN KEY(CONTACT_ID)
  REFERENCES contact (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = INNODB;

CREATE TABLE email_address (
  ID                 SERIAL,
  EMAIL_ADDRESS      VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  DESCRIPTION        VARCHAR(250) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  CONSTRAINT email_address_p PRIMARY KEY (ID),
  CONSTRAINT email_address_u UNIQUE(EMAIL_ADDRESS)
) ENGINE = INNODB;

CREATE TABLE contact_email_address (
  EMAIL_ADDRESS_ID        BIGINT UNSIGNED NOT NULL,
  CONTACT_ID              BIGINT UNSIGNED NOT NULL,
  ORDINAL_INDEX           INT UNSIGNED NOT NULL,
  CONSTRAINT contact_email_address_p PRIMARY KEY(EMAIL_ADDRESS_ID),
  CONSTRAINT contact_email_address_u UNIQUE(CONTACT_ID, ORDINAL_INDEX),
  CONSTRAINT contact_email_address_email_f
  FOREIGN KEY (EMAIL_ADDRESS_ID)
  REFERENCES email_address(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = INNODB;



