CREATE TABLE employer (
  ID            SERIAL,
  DISPLAY_NAME  VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_VALUE  VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SETTLEMENT_ID BIGINT UNSIGNED NULL,
  WEBSITE       VARCHAR(200) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  CONSTRAINT EMPLOYER_P PRIMARY KEY (ID),
  CONSTRAINT EMPLOYER_DISPLAY_U UNIQUE(DISPLAY_NAME),
  CONSTRAINT EMPLOYER_SEARCH_U  UNIQUE(SEARCH_VALUE),
  INDEX I_EMPLOYER_SETTLEMENT (SETTLEMENT_ID),
  CONSTRAINT EMPLOYER_SETTLEMENT_F FOREIGN KEY (SETTLEMENT_ID)
  REFERENCES address_settlement (ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  UNIQUE INDEX IU_EMPLOYER_WEBSITE (WEBSITE)
) ENGINE = INNODB;

CREATE TABLE employer_contact (
  CONTACT_ID           BIGINT UNSIGNED NOT NULL,
  EMPLOYER_ID          BIGINT UNSIGNED NOT NULL,
  ORDINAL_INDEX        INT UNSIGNED NOT NULL,
  CONSTRAINT employer_contact_p UNIQUE(CONTACT_ID),
  CONSTRAINT employer_contact_u UNIQUE(EMPLOYER_ID, ORDINAL_INDEX),
  INDEX employer_contact_employer_if (EMPLOYER_ID),
  CONSTRAINT employer_contact_employer_f
  FOREIGN KEY (EMPLOYER_ID)
  REFERENCES employer(ID)
    ON DELETE CASCADE,
  CONSTRAINT employer_contact_contact_f FOREIGN KEY (CONTACT_ID)
  REFERENCES contact(ID) ON DELETE CASCADE
) ENGINE = INNODB;


CREATE TABLE employer_vacancy (
  ID                  SERIAL NOT NULL,
  EMPLOYER_ID         BIGINT UNSIGNED NOT NULL,
  CONTACT_ID          BIGINT UNSIGNED NULL,
  SUMMARY             VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_VALUE        VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  DESCRIPTION         TEXT CHARSET UTF8 COLLATE utf8_unicode_ci,
  HOSTING_AVAILABLE   ENUM('NO', 'YES') NOT NULL,
  SALARY_LOW          DECIMAL(10,2) NULL,
  SALARY_HIGH         DECIMAL(10,2) NULL,
  MODIFICATION_TIME   DATETIME NOT NULL,
  OPERATOR_ID         BIGINT UNSIGNED NOT NULL,
  CONSTRAINT employer_vacancy_p PRIMARY KEY (ID),
  CONSTRAINT employer_vacancy_u UNIQUE (EMPLOYER_ID, SEARCH_VALUE),
  CONSTRAINT employer_vacancy_employer_f FOREIGN KEY(EMPLOYER_ID)
  REFERENCES employer (ID)
    ON DELETE CASCADE,
  INDEX employer_vacancy_employer_if (EMPLOYER_ID),
  CONSTRAINT employer_vacancy_operator_f FOREIGN KEY (OPERATOR_ID)
  REFERENCES user(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX employer_vacancy_operator_if (OPERATOR_ID),
  CONSTRAINT employer_vacancy_contact_f
  FOREIGN KEY (CONTACT_ID) REFERENCES contact (ID)
    ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX employer_vacancy_contact_if (CONTACT_ID),
  INDEX employer_vacancy_search_i (SEARCH_VALUE),
  INDEX employer_vacancy_search_salary (SEARCH_VALUE, SALARY_LOW, SALARY_HIGH)
) ENGINE = INNODB;




