CREATE TABLE address_region(
  ID VARCHAR(10) CHARSET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
  DISPLAY_NAME VARCHAR(40) CHARSET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
  SEARCH_VALUE VARCHAR(40) CHARSET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
  CONSTRAINT ADDRESS_REGION_P PRIMARY KEY(ID),
  CONSTRAINT ADDRESS_REGION_DISPLAY_U UNIQUE(DISPLAY_NAME),
  CONSTRAINT ADDRESS_REGION_SEARCH_U UNIQUE(SEARCH_VALUE)
) ENGINE=INNODB;

CREATE TABLE address_district (
  ID                SERIAL,
  REGION_ID         VARCHAR(10) CHARSET UTF8 COLLATE utf8_unicode_ci not null,
  DISPLAY_NAME      VARCHAR(60) CHARSET UTF8 COLLATE utf8_unicode_ci not null,
  SEARCH_VALUE      VARCHAR(60) CHARSET UTF8 COLLATE utf8_unicode_ci not null,
  MOCK_DISTRICT     ENUM('NO', 'YES') NOT NULL,
  CONSTRAINT ADDRESS_DISTRICT_P PRIMARY KEY(ID),
  CONSTRAINT ADDRESS_DISTRICT_DSPL_REG_U UNIQUE (REGION_ID, DISPLAY_NAME),
  CONSTRAINT ADDRESS_DISTRICT_SRCH_REG_U UNIQUE (REGION_ID, SEARCH_VALUE)
--CONSTRAINT ADDRESS_DISTRICT_RGN_F FOREIGN KEY (REGION_ID)  REFERENCES ADDRESS_REGION(ID)
-- ON DELETE RESTRICT
) engine = INNODB;

CREATE TABLE address_settlement (
  ID                 SERIAL,
  DISTRICT_ID        BIGINT UNSIGNED NOT NULL,
  SETTLEMENT_KIND    ENUM ('farmstead', 'village', 'town', 'city') NOT NULL,
  DISPLAY_NAME       VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_VALUE       VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  CONSTRAINT         address_settlement_p PRIMARY KEY(ID),
  CONSTRAINT         address_settlement_unique_search UNIQUE (DISTRICT_ID, SETTLEMENT_KIND, SEARCH_VALUE),
  CONSTRAINT         address_settlement_unique_display UNIQUE (DISTRICT_ID, SETTLEMENT_KIND, DISPLAY_NAME),
  CONSTRAINT         address_settle_district_f FOREIGN KEY (DISTRICT_ID)
    REFERENCES address_district(ID),
  INDEX address_settlement_district_if (DISTRICT_ID)
) ENGINE = INNODB;

CREATE TABLE address_street(
  ID SERIAL,
  SETTLEMENT_ID BIGINT UNSIGNED NOT NULL,
  STREET_KIND   ENUM('block', 'square', 'avenue', 'boulevard', 'lane',
                     'road', 'drive', 'upway', 'downway', 'street') NOT NULL,
  DISPLAY_NAME  VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_VALUE  VARCHAR(80) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  CONSTRAINT address_street_p PRIMARY KEY(ID),
  CONSTRAINT address_street_settle_f
  FOREIGN KEY (SETTLEMENT_ID) REFERENCES address_settlement(ID),
  INDEX i_address_street_search (SEARCH_VALUE ASC),
  CONSTRAINT address_street_u UNIQUE(SETTLEMENT_ID, STREET_KIND, SEARCH_VALUE),
  INDEX address_street_if (SETTLEMENT_ID)
) ENGINE = INNODB;

CREATE TABLE address_location (
  ID                    SERIAL,
  STREET_ID             BIGINT UNSIGNED NULL,
  POSTAL_CODE           VARCHAR(16)  CHARSET UTF8 COLLATE utf8_unicode_ci DEFAULT '00000',
  STREET_NUMBER         VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  SEARCH_STREET_NUMBER  VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NOT NULL,
  BLOCK_NUMBER          VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  SEARCH_BLOCK_NUMBER   VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  ROOM_NUMBER           VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  SEARCH_ROOM_NUMBER    VARCHAR(40) CHARSET UTF8 COLLATE utf8_unicode_ci NULL,
  CONSTRAINT address_location_p PRIMARY KEY (ID),
  CONSTRAINT address_location_street_f FOREIGN KEY (STREET_ID)
  REFERENCES address_street(ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  UNIQUE INDEX ui_address_location (STREET_ID, SEARCH_STREET_NUMBER, SEARCH_BLOCK_NUMBER, SEARCH_ROOM_NUMBER)
) ENGINE = INNODB;





