server:
  port: 9183
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:23306}/${DB_NAME:what-where-test}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Kiev
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:__test_master_83_}
    driver-class-name: com.mysql.cj.jdbc.Driver
# noinspection SpringBootApplicationYaml
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: ${ADMIN_USER:southpost-test-admin}
      password: ${ADMIN_PASSWORD:__77cAmaR0_99_}
    realmImportFile: southpost-realm.json